config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#                     root GET    /                                                 welcome#index
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#            user_password POST   /users/password(.:format)                         devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                          PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                           registrations#cancel
#        user_registration POST   /users(.:format)                                  registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                          registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             registrations#edit
#                          PATCH  /users(.:format)                                  registrations#update
#                          PUT    /users(.:format)                                  registrations#update
#                          DELETE /users(.:format)                                  registrations#destroy
#         article_comments GET    /articles/:article_id/comments(.:format)          comments#index
#                          POST   /articles/:article_id/comments(.:format)          comments#create
#      new_article_comment GET    /articles/:article_id/comments/new(.:format)      comments#new
#     edit_article_comment GET    /articles/:article_id/comments/:id/edit(.:format) comments#edit
#          article_comment GET    /articles/:article_id/comments/:id(.:format)      comments#show
#                          PATCH  /articles/:article_id/comments/:id(.:format)      comments#update
#                          PUT    /articles/:article_id/comments/:id(.:format)      comments#update
#                          DELETE /articles/:article_id/comments/:id(.:format)      comments#destroy
#                 articles GET    /articles(.:format)                               articles#index
#                          POST   /articles(.:format)                               articles#create
#              new_article GET    /articles/new(.:format)                           articles#new
#             edit_article GET    /articles/:id/edit(.:format)                      articles#edit
#                  article GET    /articles/:id(.:format)                           articles#show
#                          PATCH  /articles/:id(.:format)                           articles#update
#                          PUT    /articles/:id(.:format)                           articles#update
#                          DELETE /articles/:id(.:format)                           articles#destroy
#                     tags GET    /tags(.:format)                                   tags#index
#                          POST   /tags(.:format)                                   tags#create
#                  new_tag GET    /tags/new(.:format)                               tags#new
#                 edit_tag GET    /tags/:id/edit(.:format)                          tags#edit
#                      tag GET    /tags/:id(.:format)                               tags#show
#                          PATCH  /tags/:id(.:format)                               tags#update
#                          PUT    /tags/:id(.:format)                               tags#update
#                          DELETE /tags/:id(.:format)                               tags#destroy
#                categorys GET    /categorys(.:format)                              categorys#index
#                          POST   /categorys(.:format)                              categorys#create
#             new_category GET    /categorys/new(.:format)                          categorys#new
#            edit_category GET    /categorys/:id/edit(.:format)                     categorys#edit
#                 category GET    /categorys/:id(.:format)                          categorys#show
#                          PATCH  /categorys/:id(.:format)                          categorys#update
#                          PUT    /categorys/:id(.:format)                          categorys#update
#                          DELETE /categorys/:id(.:format)                          categorys#destroy
#

Rails.application.routes.draw do

	root 'welcome#index'
    devise_for :users, :controllers => { registrations: 'registrations' }

	resources :articles do
		resources :comments
	end
	resources :tags
	resources :categorys
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  view_count  :integer
#  category_id :integer
#

class Article < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :category, counter_cache: true
	has_many :comments, dependent: :destroy
	has_many :taggings

	# An article has a list of tags through the relationship of taggings
	has_many :tags, through: :taggings

	validates :title, presence: true, length: { minimum: 5,
    too_short: "%{count} characters is the maximum allowed" }

	validates :body,  presence: true, length: { minimum: 10 }
	validates :category_id, presence: true

	validates_associated :comments

	
	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end

	def increase_view_counter
		update_attributes(:view_count => view_count + 1)
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def index
		@articles = Article.all
		@popular_articles = Article.order('articles.view_count DESC').limit(3)
		@tags = Tag.all
	end

	def new
		@article = current_user.articles.build
	end

	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
		# Increment the counter using the increase_view_counter method
		@article.increment!(:view_count)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
		
	end

	def destroy
		@article = Article.find(params[:id])

		@article.destroy
		redirect_to articles_path
	end

	private

		# http://weblog.rubyonrails.org/2012/3/21/strong-parameters/
		def article_params 
			params.require(:article).permit(:title, :body, :category_id, :tag_list)
		end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li class="media list-group-item">
    <p class="media-left">
      Viewed: <%= article.view_count %> times
    </p>
    <div class="media-body">
      <div class="media-heading">
        <small class="pull-right">
            Viewed: <%= article.view_count %> times
            <% if user_signed_in? && article.user == current_user %>
              | <%= link_to "delete", article, method: :delete,
                                            data: { confirm: "You sure?" } %>
              <% end %>
        </small>
        <h5>
          Posted By: <%= article.user.first_name %> 
          <%= "#{time_ago_in_words(article.created_at)} ago" %>
        </h5>
      </div>
      <h3><%= link_to article.title, article %></h3>

      <p><%= truncate(simple_format(article.body), escape: false, length: 600) %></p>

      <%= link_to article_path(article), class: "btn btn-sm btn-primary" do %>
        Read More <span class="fa fa-arrow-right"></span>
      <% end %>

    </div>
</li>

app/views/articles/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name, 'Category' %>
<%= f.collection_select :category_id, 
	Category.all, :id, :name, 
	{ include_blank: "Choose a Category" }, class: 'form-control'%>

<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>

<%= f.label :body %>
<%= f.text_area :body, rows: 8, class: 'form-control' %>

<%= f.label :tag_list %>
<%= f.text_field :tag_list, class: 'form-control' %>

<%= button_tag(class: 'btn btn-success') do %>
	Add Article <i class="fa fa-check"></i>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for(@article) do |f| %>
	<%= render 'fields', f: f %>
<% end %>

<%= link_to articles_path, class: 'btn btn-default' do %>
	Back <i class="fa fa-chevron-left"></i>
<% end %>

app/views/articles/index.html.erb
<div class="row">
	<div class="col-md-8">

		<% if @articles.any? %>
			<ul class="list-group media-list media-list-stream">
				<%= render @articles %>
			</ul>
			<!-- pagination here  -->
		<% else %>
			<h3>Posts (0)</h3>
		<% end %>

	</div>

	<div class="col-md-4">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Tag Cloud</h3>
			</div>
			<div class="panel-body">
				<% @tags.each do |tag| %>
					<%= link_to tag.name, tag_path(tag) %>
				<% end %>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Hot Articles</h3>
			</div>
			<div class="panel-body">
				<ul>
					<% @popular_articles.each do |popular| %>
						<li><%= link_to popular.title, popular %></li>
					<% end %>
				</ul>
			</div>
		</div>

	</div>
</div>

app/views/articles/new.html.erb
<h1>Add an Article</h1>

<%= form_for(@article) do |f| %>
	<%= render 'fields', f: f %>
<% end %>

<%= link_to articles_path, class: 'btn btn-default' do %>
	Back <i class="fa fa-chevron-left"></i>
<% end %>

app/views/articles/show.html.erb
<p>Title: <%= @article.title %></p>
<p>Body:  <%= @article.body %></p>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>Posted By: <%= @article.user.first_name %> 
   and viewed <%= @article.view_count %> times
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<% if user_signed_in? %>
	<h2>Add a comment:</h2>
	<%= render 'comments/form' %>
<% end %>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>