config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#                     root GET    /                                                 welcome#index
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#            user_password POST   /users/password(.:format)                         devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                          PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                           registrations#cancel
#        user_registration POST   /users(.:format)                                  registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                          registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             registrations#edit
#                          PATCH  /users(.:format)                                  registrations#update
#                          PUT    /users(.:format)                                  registrations#update
#                          DELETE /users(.:format)                                  registrations#destroy
#         article_comments GET    /articles/:article_id/comments(.:format)          comments#index
#                          POST   /articles/:article_id/comments(.:format)          comments#create
#      new_article_comment GET    /articles/:article_id/comments/new(.:format)      comments#new
#     edit_article_comment GET    /articles/:article_id/comments/:id/edit(.:format) comments#edit
#          article_comment GET    /articles/:article_id/comments/:id(.:format)      comments#show
#                          PATCH  /articles/:article_id/comments/:id(.:format)      comments#update
#                          PUT    /articles/:article_id/comments/:id(.:format)      comments#update
#                          DELETE /articles/:article_id/comments/:id(.:format)      comments#destroy
#                 articles GET    /articles(.:format)                               articles#index
#                          POST   /articles(.:format)                               articles#create
#              new_article GET    /articles/new(.:format)                           articles#new
#             edit_article GET    /articles/:id/edit(.:format)                      articles#edit
#                  article GET    /articles/:id(.:format)                           articles#show
#                          PATCH  /articles/:id(.:format)                           articles#update
#                          PUT    /articles/:id(.:format)                           articles#update
#                          DELETE /articles/:id(.:format)                           articles#destroy
#                     tags GET    /tags(.:format)                                   tags#index
#                          POST   /tags(.:format)                                   tags#create
#                  new_tag GET    /tags/new(.:format)                               tags#new
#                 edit_tag GET    /tags/:id/edit(.:format)                          tags#edit
#                      tag GET    /tags/:id(.:format)                               tags#show
#                          PATCH  /tags/:id(.:format)                               tags#update
#                          PUT    /tags/:id(.:format)                               tags#update
#                          DELETE /tags/:id(.:format)                               tags#destroy
#                categorys GET    /categorys(.:format)                              categorys#index
#                          POST   /categorys(.:format)                              categorys#create
#             new_category GET    /categorys/new(.:format)                          categorys#new
#            edit_category GET    /categorys/:id/edit(.:format)                     categorys#edit
#                 category GET    /categorys/:id(.:format)                          categorys#show
#                          PATCH  /categorys/:id(.:format)                          categorys#update
#                          PUT    /categorys/:id(.:format)                          categorys#update
#                          DELETE /categorys/:id(.:format)                          categorys#destroy
#

Rails.application.routes.draw do

	root 'welcome#index'
    devise_for :users, :controllers => { registrations: 'registrations' }

	resources :articles do
		resources :comments
	end
	resources :tags
	resources :categorys
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('favicon.ico'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(articles_path) %>"><%= link_to "Blog", articles_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="<%= 'active' if current_page?(new_article_path) %>">
          <%= link_to 'New Article', new_article_path %>
        </li>
        <% else %>
          <li class="<%= 'active' if current_page?(new_user_session_path) %>">
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
          <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
        <% end %>

        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'New Article', new_article_path %></li>
          </ul>
        </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">

	<% if notice %>
		<div class="alert alert-info">
			<%= flash.notice %>
		</div>
	<% end %>

	<% if alert %>
		<div class="alert alert-warning">
			<%= flash.alert %>
		</div>
	<% end %>


	<%= yield %>

</div>

</body>
</html>